### ISSUE TITLE
Error while fuzzing a server during dependency analysis

### ISSUE THREAD

**Issue by sathiyajith** [Artisan-Lab/foREST#6]
(venv) # python3 foREST.py --api_file_path /5g-Microservice-testing/apis/amf_even_exposure.yaml --out_put ./output
2024-09-23 00:35:14,784 : Start parsing API file
2024-09-23 00:35:15,259 : Finish parsing API file, 3 API identified
2024-09-23 00:35:15,260 : Start dependency analysis
root     {}
└── namf-evts {}
    └── v1 {}
        └── subscriptions {'post': 0}
            └── {subscriptionId} {'delete': 1, 'patch': 2}
Traceback (most recent call last):
  File "/foREST/foREST.py", line 63, in <module>
    no_reference_field = api_list_parser().foREST_dependency_analysis()
  File "/foREST/module/parser/api_parser.py", line 92, in foREST_dependency_analysis
    key_value_parser.get_dependency()
  File "/foREST/module/parser/dependency.py", line 143, in get_dependency
    self.get_field_dependency(req_field_info)
  File "/foREST/module/parser/dependency.py", line 119, in get_field_dependency
    self.find_depend_API()
  File "/foREST/module/parser/dependency.py", line 59, in find_depend_API
    self.find_depend_field(field_info)
  File "/foREST/module/parser/dependency.py", line 84, in find_depend_field
    point = smart_match(real_field_name, self.base_parent_relation[-1], self.base_field_info.field_type,
  File "/foREST/module/parser/dependency.py", line 22, in smart_match
    match_point -= 100 - base_match_point
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

**I'm facing the above error, Is there any mistake in the command used or Should I use a different version or branch of foREST?**

**Comment by Wumaomaomao** [comment]
I ran into the same issue because I didn't use the correct command-line arguments, which was not mentioned in the repository but can be discovered through exploration. I recommend using the repository's `setting.json` file to start foREST.
`python3 foREST.py --api_file_path $API_SPEC --out_put ./result_fearues-service --target_ip $SERVICE_IP --time_budget $MAX_TIME --settings_file setting.json`
